# reports generator
# each class that allows report generation should provide
# data for generation. 
# format and content not determined now 
#
# reports should be allowed to generated in different formats
# - markdown 
# - LaTeX
# - ...
# 
# reports will be generated by separate entity with proposed name of 'report_generator'
# it will accept ordered list of entities, that can provide data for report and after report will be generated

class reportable:
	
	def get_data_for_report(self):
		pass